import { Club, Fixture, Player, SaveState } from "../types";
import { InjuryEngine } from "./InjuryEngine";
import { TransferEngine } from "./TransferEngine";
import { YouthAcademy } from "./YouthAcademy";
const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,n));
export class SimulationEngine {
 static playerRating(p:Player){const a=p.attributes;const base=p.position==="ATT"?a.finishing*.3+a.pace*.15+a.dribbling*.15+a.composure*.15+a.positioning*.15+a.stamina*.1:p.position==="MID"?a.passing*.25+a.vision*.2+a.ballControl*.15+a.stamina*.15+a.positioning*.15+a.dribbling*.1:p.position==="DEF"?a.defending*.3+a.tackling*.2+a.strength*.15+a.positioning*.15+a.pace*.1+a.passing*.1:a.reactions*.3+a.positioning*.25+a.strength*.15+a.composure*.15+a.passing*.15;return Math.round(base*.72+p.form*.16+p.fitness*.12)}
 static calculateTeamStrength(c:Club){return c.players.length?Math.round(c.players.reduce((s,p)=>s+this.playerRating(p),0)/c.players.length):0}
 static simulateFixture(club:Club,fixture:Fixture):Fixture{const s=this.calculateTeamStrength(club)+(fixture.homeClubId===club.id?4:0);const x=Math.max(.2,(s-60)/20+(Math.random()-.5));const ox=Math.max(.2,1.2+(Math.random()-.5));const g=Math.max(0,Math.round(x+(Math.random()-.5)*1.8));const og=Math.max(0,Math.round(ox+(Math.random()-.5)*1.8));return {...fixture,result:`${g}-${og}`,xg:`${x.toFixed(2)} - ${ox.toFixed(2)}`}}
 static advanceDay(state:SaveState):SaveState{const d=new Date(state.currentDate);d.setDate(d.getDate()+1);const club={...state.club,players:state.club.players.map(p=>{let n=InjuryEngine.recover(p);const load=n.injury?2:5;n=InjuryEngine.maybeInjure(n,load);const form=clamp(n.form+(Math.random()-.5)*1.2);const dev=n.age<=21?.05:n.age<=26?.02:n.age>=32?-.03:0;return {...n,form,overall:clamp(n.overall+dev,1,99),potential:clamp(n.potential+dev*.5,1,99)}})};return {...state,currentDate:d.toISOString().slice(0,10),club}}
 static simulateNextMatch(state:SaveState):SaveState{const i=state.fixtures.findIndex(f=>!f.result);if(i<0)return state;const f=this.simulateFixture(state.club,state.fixtures[i]);const [gf,ga]=f.result!.split("-").map(Number);const club={...state.club,players:state.club.players.map(p=>({...p,appearances:p.appearances+1,goals:p.goals+(p.position==="ATT"&&gf>0&&Math.random()<.35?1:0),assists:p.assists+(p.position==="MID"&&gf>0&&Math.random()<.25?1:0),form:clamp(p.form+(gf>ga?1.5:gf<ga?-1:.2)),fitness:clamp(p.fitness-8)}))};return {...state,club,fixtures:state.fixtures.map((x,j)=>j===i?f:x),news:[`${club.name} ${f.result} ${f.away}`,...state.news].slice(0,20)}}
 static simulateWeek(state:SaveState):SaveState{let n=state;for(let i=0;i<7;i++)n=this.advanceDay(n);return n}
 static generateYouth(state:SaveState):SaveState{const youth=YouthAcademy.generate(state.club,Number(state.currentDate.slice(0,4)));return {...state,club:{...state.club,players:[...state.club.players,youth]},news:[`Youth academy promoted ${youth.name}, a ${youth.position} with ${youth.potential} potential.`,...state.news]}}
 static aiTransfers(state:SaveState):SaveState{const offers=TransferEngine.aiTransfer(state.clubs,state.season);return {...state,transferOffers:[...state.transferOffers,...offers],news:[...offers.map(o=>`Transfer negotiation opened for ${o.playerId}.`),...state.news].slice(0,20)}}
}