import { useEffect, useMemo, useState } from "react";
import { Activity, Bell, CalendarDays, ChevronRight, CircleDollarSign, Dumbbell, Home, Inbox, Search, Settings, Shield, Trophy, Users, Zap, HeartPulse, Globe2, BarChart3, UserRound, ArrowRightLeft, Building2, Clock3 } from "lucide-react";
import { worldClubs, leagues, nationalTeams, tournaments } from "./data/world";
import { SimulationEngine } from "./engine/SimulationEngine";
import { loadGame, saveGame } from "./storage";
import { Club, Fixture, League, NationalTeam, SaveState, Tournament } from "./types";

const initialClub=worldClubs[0];
const initialFixtures:Fixture[]=[
 {id:"f1",homeClubId:"mun",awayClubId:"ars",home:"Manchester United",away:"Arsenal",competition:"Premier League",type:"League",date:"2026-08-08"},
 {id:"f2",homeClubId:"mun",awayClubId:"bay",home:"Manchester United",away:"Bayern Munich",competition:"Champions League",type:"Continental",date:"2026-08-19"},
 {id:"f3",homeClubId:"liv",awayClubId:"mun",home:"Liverpool",away:"Manchester United",competition:"Premier League",type:"League",date:"2026-08-23"},
 {id:"f4",homeClubId:"mun",awayClubId:"mci",home:"Manchester United",away:"Manchester City",competition:"Premier League",type:"League",date:"2026-09-06"}
];
const money=(v:number)=>new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD",maximumFractionDigits:0}).format(v);
export default function App(){
 const [club,setClub]=useState<Club>(initialClub),[clubs,setClubs]=useState<Club[]>(worldClubs),[leaguesState,setLeagues]=useState<League[]>(leagues),[fixtures,setFixtures]=useState<Fixture[]>(initialFixtures),[teams,setTeams]=useState<NationalTeam[]>(nationalTeams),[cups,setCups]=useState<Tournament[]>(tournaments),[offers,setOffers]=useState<SaveState["transferOffers"]>([]),[date,setDate]=useState("2026-07-26"),[active,setActive]=useState("Overview"),[message,setMessage]=useState("Stage 3 world simulation systems are online.");
 const state=useMemo<SaveState>(()=>({currentDate:date,club,clubs,leagues:leaguesState,fixtures,nationalTeams:teams,tournaments:cups,transferOffers:offers,news:[],season:2026}),[date,club,clubs,leaguesState,fixtures,teams,cups,offers]);
 useEffect(()=>{loadGame().then(s=>{if(s){setDate(s.currentDate);setClub(s.club);setClubs(s.clubs||worldClubs);setLeagues(s.leagues||leagues);setFixtures(s.fixtures||initialFixtures);setTeams(s.nationalTeams||nationalTeams);setCups(s.tournaments||tournaments);setOffers(s.transferOffers||[])}})},[]);
 const persist=async(n:SaveState)=>{setDate(n.currentDate);setClub(n.club);setClubs(n.clubs);setLeagues(n.leagues);setFixtures(n.fixtures);setTeams(n.nationalTeams);setCups(n.tournaments);setOffers(n.transferOffers);await saveGame(n)};
 const action=async(kind:string)=>{let n=state;if(kind==="day")n=SimulationEngine.advanceDay(state);if(kind==="week")n=SimulationEngine.simulateWeek(state);if(kind==="match")n=SimulationEngine.simulateNextMatch(state);if(kind==="youth")n=SimulationEngine.generateYouth(state);if(kind==="transfers")n=SimulationEngine.aiTransfers(state);await persist(n);setMessage(kind==="youth"?"Youth intake completed.":kind==="transfers"?`${n.transferOffers.length} AI transfer negotiations are active.`:"World simulation advanced successfully.")};
 const nav=[["Overview",Home],["Squad",Users],["Schedule",CalendarDays],["Transfers",ArrowRightLeft],["Training",Dumbbell],["Medical",HeartPulse],["Competitions",Trophy],["National Teams",Shield],["World",Globe2],["History",Activity]] as const;
 const next=fixtures.find(f=>!f.result);
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">⚽</div><div><strong>FOOTBALL GM</strong><span>SIMULATOR</span></div></div><div className="club-mini"><div className="crest">MU</div><div><strong>{club.name}</strong><span>{club.league}</span></div><ChevronRight size={16}/></div><nav>{nav.map(([label,Icon])=><button className={active===label?"nav-item active":"nav-item"} onClick={()=>setActive(label)} key={label}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Settings size={18}/><span>Settings</span></button><div className="save-status"><span className="dot"/> Autosave enabled</div></div></aside>
 <main className="main"><header className="topbar"><div className="breadcrumbs"><span>Home</span><ChevronRight size={14}/><strong>{active}</strong></div><div className="top-actions"><div className="date-pill"><CalendarDays size={16}/>{date}</div><button className="icon-button"><Search size={18}/></button><button className="icon-button"><Bell size={18}/></button><button className="avatar">FM</button></div></header>
 <section className="content"><div className="page-title"><div><p className="eyebrow">GLOBAL FOOTBALL UNIVERSE</p><h1>{club.name}</h1><p className="muted">{club.country} · {club.league} · {clubs.length} clubs loaded · {teams.length} national teams loaded</p></div><div className="action-row"><button className="secondary" onClick={()=>action("day")}><Zap size={16}/> Simulate Day</button><button className="secondary" onClick={()=>action("week")}><CalendarDays size={16}/> Simulate Week</button><button className="secondary" onClick={()=>action("youth")}><Users size={16}/> Youth Intake</button><button className="primary" onClick={()=>action("match")}>▶ Simulate Match</button></div></div><div className="notice"><Inbox size={16}/>{message}</div>
 <div className="stats-grid"><StatCard title="Club Balance" value={money(club.balance)} change="Contracts + transfers" icon={<CircleDollarSign/>}/><StatCard title="Squad Strength" value={`${SimulationEngine.calculateTeamStrength(club)}`} change="Attribute + form model" icon={<Shield/>}/><StatCard title="Next Match" value={next?.away??"No fixture"} change={next?.competition??"Season complete"} icon={<CalendarDays/>}/><StatCard title="World Systems" value={`${clubs.length} clubs`} change={`${offers.length} transfer negotiations`} icon={<Globe2/>}/></div>
 <div className="tabs">{["Dashboard","Squad","Leagues","Transfers","National Teams","World Cup"].map(t=><button className={active===t?"tab active":"tab"} onClick={()=>setActive(t)} key={t}>{t}</button>)}</div>
 {active==="Overview"||active==="Dashboard"?<Dashboard club={club} fixtures={fixtures} teams={teams} leagues={leaguesState} cups={cups} offers={offers} action={action}/>:active==="Squad"?<Squad club={club}/>:active==="Leagues"?<Leagues leagues={leaguesState} clubs={clubs}/>:active==="Transfers"?<Transfers offers={offers}/>:active==="National Teams"?<NationalTeams teams={teams}/>:active==="World Cup"?<WorldCup cups={cups}/>:<Dashboard club={club} fixtures={fixtures} teams={teams} leagues={leaguesState} cups={cups} offers={offers} action={action}/>}
 </section></main></div>
}
function PanelTitle({eyebrow,title}:{eyebrow:string,title:string}){return <div className="panel-header"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div></div>}
function StatCard({title,value,change,icon}:{title:string,value:string,change:string,icon:React.ReactNode}){return <div className="stat-card"><div className="stat-icon">{icon}</div><div><span>{title}</span><strong>{value}</strong><small>{change}</small></div></div>}
function Dashboard({club,fixtures,teams,leagues,cups,offers,action}:{club:Club,fixtures:Fixture[],teams:NationalTeam[],leagues:League[],cups:Tournament[],offers:SaveState["transferOffers"],action:(x:string)=>void}){return <div className="dashboard-grid"><section className="panel large"><PanelTitle eyebrow="UPCOMING" title="Global Schedule"/><div className="fixture-list">{fixtures.map(f=><div className="fixture" key={f.id}><div className="fixture-date"><strong>{f.date.slice(8)}</strong><span>{f.date.slice(5,7)}</span></div><div className="fixture-main"><strong>{f.home} vs {f.away}</strong><span>{f.competition}</span></div><div className={f.result?"result played":"result"}>{f.result??"UPCOMING"}</div></div>)}</div></section><section className="panel"><PanelTitle eyebrow="WORLD" title="Leagues & Clubs"/><div className="status-list">{leagues.map(l=><div className="status-row" key={l.id}><span>{l.name}</span><strong>{l.clubs.length} clubs</strong></div>)}</div><button className="secondary wide" onClick={()=>action("transfers")}><ArrowRightLeft size={15}/> Run AI Transfer Window</button></section><section className="panel"><PanelTitle eyebrow="YOUTH DEVELOPMENT" title="Academy"/><div className="world-card"><div className="world-icon"><Users size={24}/></div><div><strong>Generate new academy prospect</strong><span>16–21-year-old prospects with probabilistic potential.</span></div></div><button className="secondary wide" onClick={()=>action("youth")}><Building2 size={15}/> Generate Youth Intake</button></section><section className="panel large"><PanelTitle eyebrow="INTERNATIONAL CALENDAR" title="World Competitions"/><div className="mini-table">{cups.map(c=><div key={c.id}><span>{c.year}</span><strong>{c.name}</strong><em>{c.type}</em></div>)}</div></section></div>}
function Squad({club}:{club:Club}){return <section className="panel full"><PanelTitle eyebrow="FULL SQUAD" title={`${club.name} First Team`}/><div className="table">{club.players.map(p=><div className="table-row" key={p.id}><UserRound size={17}/><strong>{p.name}</strong><span>{p.position}</span><span>{p.nationality}</span><span>Age {p.age}</span><b>{p.overall}</b><em>{Math.round(p.form)} form</em><small>{p.injury?`${p.injury.type} · ${p.injury.weeksRemaining}w`:"Available"}</small></div>)}</div></section>}
function Leagues({leagues,clubs}:{leagues:League[],clubs:Club[]}){return <section className="panel full"><PanelTitle eyebrow="DOMESTIC FOOTBALL" title="League System"/><div className="team-grid">{leagues.map(l=><div className="team-card" key={l.id}><div className="team-code">{l.country.slice(0,3).toUpperCase()}</div><div><strong>{l.name}</strong><span>Level {l.level} · Season {l.currentSeason}</span><small>{l.clubs.map(id=>clubs.find(c=>c.id===id)?.shortName||id).join(" · ")}</small></div><b>{l.clubs.length}</b></div>)}</div></section>}
function Transfers({offers}:{offers:SaveState["transferOffers"]}){return <section className="panel full"><PanelTitle eyebrow="TRANSFER MARKET" title="AI Negotiations"/><div className="table">{offers.length?offers.map(o=><div className="table-row" key={o.id}><ArrowRightLeft size={17}/><strong>{o.playerId}</strong><span>{o.fromClubId}</span><span>→ {o.toClubId}</span><span>{money(o.fee)}</span><b>{o.status}</b><em>Wage {money(o.wage)}</em><small>Market model</small></div>):<div className="notice">No active negotiations. Run the AI transfer window from the dashboard.</div>}</div></section>}
function NationalTeams({teams}:{teams:NationalTeam[]}){return <section className="panel full"><PanelTitle eyebrow="INTERNATIONAL FOOTBALL" title="National Teams"/><div className="team-grid">{teams.map(t=><div className="team-card" key={t.code}><div className="team-code">{t.code}</div><div><strong>{t.name}</strong><span>World Ranking #{t.ranking}</span><small>{t.manager}</small></div><b>{t.wins}-{t.draws}-{t.losses}</b></div>)}</div></section>}
function WorldCup({cups}:{cups:Tournament[]}){return <section className="panel full"><PanelTitle eyebrow="GLOBAL COMPETITIONS" title="World Cup Cycles & International Calendar"/><div className="history-grid">{cups.map(c=><div key={c.id}><Trophy/><strong>{c.name}</strong><span>{c.year} · {c.startDate} → {c.endDate}</span><small>{c.teams.length} teams currently loaded</small></div>)}</div></section>}
